### ISSUE TITLE
Issue when using inference script

### ISSUE THREAD

**Issue by fervillamar** [prairie-schooner/wav2vec-vc#1]
Hi, awesome work, thanks.  I get this error when using inference.py, any idea how to solve it?, thanks in advance!

Traceback (most recent call last):
  File "/workspace/wav2vec-vc/inference.py", line 65, in <module>
    inference(
  File "/workspace/wav2vec-vc/inference.py", line 46, in inference
    wav = vocoder.generate([dec.squeeze(0), ])[0].to('cpu')
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/universal_vocoder.py", line 58, in generate
....

**Comment by exercise-book-yq** [comment]
@fervillamar I got the same problem. Do you solve it now?
